### PR TITLE
Support python 3.5

### PR DESCRIPTION
**Pull request by baaym**
# Description

Since there's still a lot of Python 3.5 being used in the community, including us, we've taken the opportunity to make the python client compatible with Python 3.5.
Fortunately there wasn't a lot of code making use of newer language features, so the impact is relatively low. The test coverage is excellent, so the few things that did need to change were easy to spot.

## Type of change

- [ x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

All existing tests have been run and pass

- [x ] Unit tests
- [ x] Spec Tests
- [ x] Integration tests / Manual Tests

# Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ivanklee86** [comment]
Thanks for the PR!  I'm a little behind on my unleash-related chores - I'll take a look in the next few days! ^^

**Comment by baaym** [comment]
Hi @ivanklee86,

No worries! I also just rebased onto master and fixed the mypy complaint. The build is now completely green.

**Comment by baaym** [comment]
Hi @ivanklee86,

Have you been able to look at this PR yet?
I also have another small improvement that I'd like to send a PR for, but it depends on this one to be merged first.

**Comment by ivanklee86** [comment]
@baaym 

Heya!

Apologies for the radio silence - my work / personal life took a few weird turns over the last few weeks. >_o

After chewing on your PR this AM, I wanted to address a few things before landing this PR:
* Set up tox to run tests against different versions of Python.  (Reason: I'd like to support Python 3.5 but still automatically check that Python 3.7 keeps working.)
* Set up ^ for CI.
* Remove pipenv. (Reason: It's solve for library development is basically to give up everything in the `package.lock` equiv.  I'd rather just use pip + maybe conda.)

I'm hoping to get ^ done over the weekend.  (Some preliminary work is [here|https://github.com/Unleash/unleash-client-python/tree/il/tox_and_ci].  I've seen a few things-to-fix that I believe you addressed in this PR. :) )

Out of curiosity, how do you do local development?  I had some issues installing mmh3 using Python 3.5 on my Mac.

**Pull request merged**
