### PR TITLE
Cache abstraction

### LINKED ISSUE #126: Support different types of caching, like in-memory or redis caching
**Is your feature request related to a problem?**

I cannot use unleash-client-python as it needs to create a caching directory and this is not possible as  I have an app deployed on Google App Engine and it's read only file system.

**Describe the solution you'd like**

Support different types of caching, like in-memory or redis caching.

**Describe alternatives you've considered**

I'm blocked as the only way you support is File caching with filecache lib

### PR DESCRIPTION
**Pull request by walison17**
# Description

provides a cache abstraction, which makes it easier to support different types of cache.

Fixes #126

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Unit tests
- [ ] Spec Tests
- [x] Integration tests / Manual Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by damjankuznar** [comment]
@walison17 Will these changes also be able to support https://github.com/grantjenks/python-diskcache ?

**Review by snuderl — APPROVED** [review]

**Comment by ivanklee86** [comment]
Thanks for the PR!  I'm in a little bit of a busy time @ work but will try and review this week. :)

**Comment by Meemaw** [comment]
@ivanklee86 any change you could take a look a this? We're seeing a lot of issues with the default cache implementation, and would like to plug our own.

**Comment by ivanklee86** [comment]
Sorry, last week ended up being busier than expected. :)

CI is failing due to issues w/ mypy & kwargs.  Locally things look good - will merge and fix that separately.  Will probably look into a major package release later this week. :)

**Pull request merged**
