### PR TITLE
add types-requests dependency to fix the build with mypy 0.900+

### PR DESCRIPTION
**Pull request by wbolster**
see title

### CODE REVIEW

**Comment by wbolster** [comment]
the remaining CI failures are due to missing tokens/auth

**Comment by wbolster** [comment]
the remaining CI failures are due to missing tokens/auth

**Review by ivarconr — APPROVED** [review]

**Comment by ivanklee86** [comment]
Thanks for the PR!  I'll look and see if I can make the coverage report work for forks. :)

**Comment by ivanklee86** [comment]
This is released in v4.4.1!

**Comment by wbolster** [comment]
that was quick, thanks :heart_eyes_cat:

**Pull request merged**
