### PR TITLE
feat: add request timeout and request retries parameters and override…

### PR DESCRIPTION
**Pull request by snosratiershad**
… constant value

[related issue] (https://github.com/Unleash/unleash-client-python/issues/264)

I'will check and fill the checklists below soon.

# Description

Please include a summary of the change and which issue is fixed (if any).

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [ ] Unit tests
- [ ] Spec Tests
- [ ] Integration tests / Manual Tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by snosratiershad** [comment]
Looks there is some linting issues from past. please don't merge it until I fix it.

**Comment by snosratiershad** [comment]
I fixed the linting issues and we can merge it now

**Review by sighphyre — APPROVED** [review]
Thank you! LGTM

**Comment by kmkr** [comment]
Fantastic, thanks :raised_hands: Looking forward to the release of this feature :hugs:

**Pull request merged**
