### PR TITLE
Add retries to get features

### LINKED ISSUE #217: Add retries to get_feature_toggles
**Is your feature request related to a problem? Please describe.**
HTTP requests in get_feature_toggles might fail due to intermittent network issues. 

Since this is called quite often, it could create plenty of long stack traces, since the entire stack trace is printed: https://github.com/Unleash/unleash-client-python/blob/main/UnleashClient/api/features.py#L67

**Describe the solution you'd like**
Retry the request a couple of times and log only in situations where it does not recover.

I'd be happy to provide a proposal fo this.

### PR DESCRIPTION
**Pull request by janboll**
# Description

Create session and provide it with a custom HTTPAdapter, that has max_retries set.

Fixes #217 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

- [x] Unit tests
- [x] Spec Tests
- [x] Integration tests / Manual Tests

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by sighphyre — APPROVED** [review]
Awesome, really appreciate you running with this.

This looks good to me!

**Comment by ilee-asapp** [comment]
Sorry, I've been on vacation and am slowly catching up with life. >_O

I'll take a peek at the CI/CD failure tonight and cut a release once that's fixed!

**Comment by povilasb** [comment]
Thank you!
I'm eagerly waiting for this to be released :)

**Comment by ivanklee86** [comment]
This PR is in v5.3.0 which is up on Pypi now! :)

**Comment by povilasb** [comment]
Would be cool to retry all HTTP requests coming from this lib btw :)
e.g. metrics reporting: https://github.com/Unleash/unleash-client-python/blob/1861dd9ced7bf1d4c45eab949d5250280b9883e7/UnleashClient/api/metrics.py#L28

**Pull request merged**
